name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        default: 3.12.0

jobs:
  Build:
    runs-on: ubuntu-24.04-arm
    container:
      image: dtcooper/raspberrypi-os:bullseye
    steps:
      - name: Install basics
        run: |
          apt update
          apt install -y git make clisp build-essential tree
          clisp --version
      - name: Checkout SBCL
        run: git clone git://git.code.sf.net/p/sbcl/sbcl --depth 1 --branch sbcl-2.5.5 
      - name: Build SBCL
        working-directory: sbcl
        run: |
          ./make.sh --xc-host='clisp'
          ./install.sh
          sbcl --version
      - name: Install dependencies
        # Ref: https://github.com/atlas-engineer/nyxt/blob/3.12.0/documents/README.org
        run: apt install -y libwebkit2gtk-4.0-dev gobject-introspection glib-networking gsettings-desktop-schemas libfixposix-dev pkg-config xclip enchant-2 libssl-dev
        # libglib2.0-dev provides libgobject-2.0.so
        # libwebkit2gtk-4.1-dev
      - name: Checkout atlas-engineer/nyxt
        uses: actions/checkout@v4
        with:
          repository: atlas-engineer/nyxt
          path: nyxt
          ref: ${{ inputs.ref }}
          submodules: 'recursive'
          fetch-depth: 1
      - name: Make
        working-directory: nyxt
        env:
          LISP: clisp
        run: make all -j
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: nyxt
          path: nyxt/nyxt
