name: Build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-24.04-arm
    container:
      image: dtcooper/raspberrypi-os:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get install sbcl libwebkit2gtk-4.1-dev
      - name: Checkout atlas-engineer/nyxt
        uses: actions/checkout@v4
        with:
          repository: atlas-engineer/nyxt
          path: nyxt
          ref: 3.12.0
          submodules: 'recursive'
          fetch-depth: 1
      - name: Make
        working-directory: nyxt
        run: make all -j
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: nyxt
          path: nyxt/nyxt
